# File: docker-compose.yml
# Author: Marc Bria UAB (marc.bria@uab.es)

services:
  db:
    image: mariadb:10.9
    env_file:
      - .env
    container_name: "pkp_db_${COMPOSE_PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-pkpPwd}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-pkp}"
      MYSQL_USER: "${MYSQL_USER:-pkp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-pkpPwd}"
    volumes:
      - sql_mariadb:/var/lib/mysql
      - ./volumes/logs/db:/var/log/mysql
#      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
      - ./volumes/migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  app:
    image: local/${PKP_TOOL}:${PKP_VERSION}
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: "pkp_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      # Keep host and container sync:
      - /etc/localtime:/etc/localtime
      - files:/var/www/files
      - html:/var/www/html
      - public:/var/www/html/public
      - ./volumes/prepare/ojs-specific.sh:/usr/local/bin/ojs-specific
      - ./volumes/logs/app:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
#      - ./volumes/config/ojs.config.inc.php:/var/www/html/config.inc.php
      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
      - ./volumes/config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

    networks:
      - inside
    depends_on:
      - db
    restart: always

networks:
  inside:
    external: false

volumes:
  sql_mariadb:
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '\\wsl.localhost\Ubuntu-22.04\home\mvitalis\docker-volumes\html'
  files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '\\wsl.localhost\Ubuntu-22.04\home\mvitalis\docker-volumes\files'
  public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '\\wsl.localhost\Ubuntu-22.04\home\mvitalis\docker-volumes\public'